package br.com.hebert.citymanager.domain.model;

import lombok.*;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.math.BigDecimal;

@Entity
@Table(name = "city")
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class City extends GenericEntity {
    private static final long serialVersionUID = 6177165491746261349L;

    @Id // Sets the id field as the primary key in the database table
    @Column(name = "id") // Sets the column name for the id property
    @GeneratedValue(strategy = GenerationType.AUTO) // States that the id field should be autogenerated
    private Long id;

    @NotNull
    @Column(name = "ibge_id", unique=true) // Sets the column name for the id property
    private Long ibgeId;

    @NotBlank
    @Column(name = "name")
    private String name;

    @NotBlank
    @Size(min = 2, max = 2)
    @Column(name = "uf")
    private String uf;

    @Column(name = "capital")
    private Boolean capital;

    @NotNull
    @Column(name = "lon")
    private BigDecimal lon;

    @NotNull
    @Column(name = "lat")
    private BigDecimal lat;

    @Column(name = "no_accents")
    private String noAccents;

    @Column(name = "alternative_names")
    private String alternativeNames;

    @Column(name = "microregion")
    private String microRegion;

    @Column(name = "mesoregion")
    private String mesoRegion;

}
